"""Static NIFTY50 universe (cash equities) in FYERS symbol format.

Note:
- FYERS equity symbol format is typically: NSE:<SYMBOL>-EQ
- This list may need minor adjustments if FYERS uses a different suffix for any symbol.

We start static to avoid introducing a dependency on instrument-master downloads.
"""

NIFTY50 = [
    "NSE:ADANIENT-EQ",
    "NSE:ADANIPORTS-EQ",
    "NSE:APOLLOHOSP-EQ",
    "NSE:ASIANPAINT-EQ",
    "NSE:AXISBANK-EQ",
    "NSE:BAJAJ-AUTO-EQ",
    "NSE:BAJFINANCE-EQ",
    "NSE:BAJAJFINSV-EQ",
    "NSE:BPCL-EQ",
    "NSE:BHARTIARTL-EQ",
    "NSE:BRITANNIA-EQ",
    "NSE:CIPLA-EQ",
    "NSE:COALINDIA-EQ",
    "NSE:DRREDDY-EQ",
    "NSE:EICHERMOT-EQ",
    "NSE:GRASIM-EQ",
    "NSE:HCLTECH-EQ",
    "NSE:HDFCBANK-EQ",
    "NSE:HDFCLIFE-EQ",
    "NSE:HEROMOTOCO-EQ",
    "NSE:HINDALCO-EQ",
    "NSE:HINDUNILVR-EQ",
    "NSE:ICICIBANK-EQ",
    "NSE:ITC-EQ",
    "NSE:INDUSINDBK-EQ",
    "NSE:INFY-EQ",
    "NSE:JSWSTEEL-EQ",
    "NSE:KOTAKBANK-EQ",
    "NSE:LT-EQ",
    "NSE:M&M-EQ",
    "NSE:MARUTI-EQ",
    "NSE:NTPC-EQ",
    "NSE:NESTLEIND-EQ",
    "NSE:ONGC-EQ",
    "NSE:POWERGRID-EQ",
    "NSE:RELIANCE-EQ",
    "NSE:SBILIFE-EQ",
    "NSE:SBIN-EQ",
    "NSE:SUNPHARMA-EQ",
    "NSE:TCS-EQ",
    "NSE:TATACONSUM-EQ",
    "NSE:TATAMOTORS-EQ",
    "NSE:TATASTEEL-EQ",
    "NSE:TECHM-EQ",
    "NSE:TITAN-EQ",
    "NSE:ULTRACEMCO-EQ",
    "NSE:WIPRO-EQ",
    "NSE:LTIM-EQ",
    "NSE:DIVISLAB-EQ",
    "NSE:SHRIRAMFIN-EQ",
]
